# Generated by Django 5.2.4 on 2025-07-14 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('limit_date', models.DateField()),
                ('target_hours', models.IntegerField(blank=True, null=True)),
                ('progress_hours', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'En progreso'), ('completed', 'Concluido'), ('missed', 'Fuera de tiempo'), ('cancelled', 'Cancelado')], max_length=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'En progreso'), ('completed', 'Concluido'), ('cancelled', 'Cancelado')], max_length=15)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studyplan')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='studyplan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.subject'),
        ),
    ]
