# Generated by Django 5.2.4 on 2025-07-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
