# Generated by Django 5.2.4 on 2025-07-21 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_subject_teacher_classschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='study.subject'),
        ),
    ]
