# Generated by Django 5.2.4 on 2025-07-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_classschedule_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.CharField(blank=True, default='Sin asignar', max_length=50, null=True),
        ),
    ]
