# Generated by Django 5.2.4 on 2025-07-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('Green', 'Verde'), ('Lemon', 'Limon'), ('Turquoise', 'Turquesa'), ('Blue', 'Azul'), ('Violet', 'Violeta'), ('Purple', 'Morado'), ('Wine', 'Vino'), ('Red', 'Rojo'), ('Tangerine', 'Mandarina'), ('Orange', 'Naranja'), ('Yellow', 'Amarillo')]),
        ),
    ]
