# Generated by Django 5.2.4 on 2025-07-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('green', 'Verde'), ('lime', 'Limon'), ('teal', 'Turquesa'), ('blue', 'Azul'), ('violet', 'Violeta'), ('purple', 'Morado'), ('wine', 'Vino'), ('red', 'Rojo'), ('tangerine', 'Mandarina'), ('orange', 'Naranja'), ('yellow', 'Amarillo')]),
        ),
    ]
