# Generated by Django 5.2.4 on 2025-07-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_alter_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En progreso'), ('completed', 'Completada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='study.studyplan'),
        ),
    ]
