# Generated by Django 5.2.4 on 2025-07-14 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notificacion', max_length=15)),
                ('message', models.CharField(max_length=100)),
                ('reminder_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('reminder', 'Recordatorio'), ('alert', 'Alerta')])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
